version: "3.8"

services:

  frontend:
    build: ./frontend/app

    ports:
      - "3000:5173"

    volumes:
      - ./frontend/app:/app
      - /app/node_modules

    command: npm run dev -- --host

    depends_on:
      - backend

  backend:
    build: ./backend

    ports:
      - "5000:5000"

    volumes:
      - ./backend:/app
      - /app/node_modules

    command: npm run dev

    depends_on:
      - mongodb

    env_file:
      - ./backend/.env

  mongodb:
    image: mongo:6

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    restart: always

volumes:
  mongo_data: