const careers = [
// ===================== TECH / CODING =====================
// ===================== TECH / CODING =====================

  {
    name: "Frontend Developer",
    domain: "Tech",
    suitableEducationLevels: ["Class 11–12", "College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Design", "Maths"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Design and implement user interfaces using HTML, CSS, and JavaScript frameworks. Ideal for students who enjoy building interactive websites and apps."
  },
  {
    name: "Backend Developer",
    domain: "Tech",
    suitableEducationLevels: ["Class 11–12", "College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Maths"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Work on server-side logic, databases, and APIs. Requires analytical thinking and programming skills."
  },
  {
    name: "Full Stack Developer",
    domain: "Tech",
    suitableEducationLevels: ["Class 11–12", "College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Design", "Maths"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Combine frontend and backend skills to build complete web applications."
  },
  {
    name: "AI / ML Engineer",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Coding", "Maths", "Logic", "AI"],
    suitableLearningStyles: ["Theory + Practice", "Mixed"],
    requiredResources: ["Laptop", "Internet", "High-performance Computer (optional)"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Develop AI models, machine learning algorithms, and intelligent systems. Requires strong maths, programming, and analytical skills."
  },
  {
    name: "Data Scientist",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Coding", "Data Analysis"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Analyze large datasets, extract insights, and build predictive models using statistics and programming."
  },
  {
    name: "Data Engineer",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Data", "Databases"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design and manage data pipelines, databases, and data warehouses for large-scale data processing."
  },
  {
    name: "Cybersecurity Analyst",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Networking", "Security"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Protect systems and networks from cyber threats. Includes penetration testing, monitoring, and security strategy."
  },
  {
    name: "Cloud Engineer",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Networking", "Cloud Platforms"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Cloud Account"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design, deploy, and manage cloud infrastructure and services on platforms like AWS, Azure, or GCP."
  },
  {
    name: "DevOps Engineer",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Automation", "Cloud"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Bridge development and operations by automating deployments, CI/CD pipelines, and infrastructure management."
  },
  {
    name: "Blockchain Developer",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Coding", "Maths", "Crypto"],
    suitableLearningStyles: ["Theory + Practice", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Develop decentralized applications (DApps), smart contracts, and blockchain solutions."
  },
  {
    name: "Mobile App Developer",
    domain: "Tech",
    suitableEducationLevels: ["Class 11–12", "College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Design", "Mobile Tech"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Build apps for iOS and Android using native or cross-platform frameworks like Flutter or React Native."
  },
  {
    name: "Game Developer",
    domain: "Tech",
    suitableEducationLevels: ["Class 11–12", "College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Design", "Creativity", "Maths"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design and build interactive video games using engines like Unity or Unreal Engine."
  },
  {
    name: "AR / VR Developer",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Coding", "Design", "3D Modeling", "Creativity"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "VR/AR Equipment (optional)"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Develop augmented and virtual reality applications for gaming, education, and simulations."
  },
  {
    name: "IoT Engineer",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Coding", "Hardware", "Networking"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "IoT Devices (optional)"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design and manage connected devices and sensors for smart homes, cities, and industries."
  },
  {
    name: "Robotics Engineer",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Coding", "Electronics", "Maths", "Mechanics"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Robotics Kit (optional)"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Design, build, and program robots for industry, research, and entertainment."
  },
  {
    name: "Quantum Computing Researcher",
    domain: "Tech",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Maths", "Physics", "Coding", "Quantum Theory"],
    suitableLearningStyles: ["Theory-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 5,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Work on quantum algorithms and computing using principles of quantum mechanics."
  },
  {
    name: "Astronomy / Space Tech Engineer",
    domain: "Tech",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Physics", "Maths", "Engineering", "Coding"],
    suitableLearningStyles: ["Theory + Practice"],
    requiredResources: ["Laptop", "Internet", "Telescopes / Simulation Tools (optional)"],
    minimumStudyTime: 5,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Work on space missions, satellite technology, astrophysics simulations, or astronomy software."
  },
  {
    name: "AI Prompt Engineer",
    domain: "Tech",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["AI", "Coding", "Writing", "Logic"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Specialize in designing effective prompts and interactions for AI models like ChatGPT."
  }
,

// ===================== MATHEMATICS & ANALYTICS =====================

  {
    name: "Statistician",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Coding", "Business"],
    suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Books", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Analyze numerical data to provide insights. Suitable for students with strong analytical skills."
  },
  {
    name: "Actuary",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Maths", "Business", "Finance"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Assess financial risk using math and statistics. Ideal for detail-oriented and analytical students."
  },
  {
    name: "Quantitative Analyst",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Maths", "Coding", "Finance"],
    suitableLearningStyles: ["Practice-based", "Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Use mathematical models to analyze financial data. Requires coding and analytical skills."
  },
  {
    name: "Applied Mathematician",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Science"],
    suitableLearningStyles: ["Reading", "Mixed", "Practice-based"],
    requiredResources: ["Books", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Apply mathematical methods to solve real-world problems in science, technology, or business."
  },
  {
    name: "Operations Research Analyst",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Business"],
    suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Books", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Optimize business or organizational processes using mathematical models."
  },
  {
    name: "Data Analyst",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Coding", "Business"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Excel/SQL/BI Tools"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Collect, process, and perform statistical analyses on datasets to guide decisions."
  },
  {
    name: "Data Scientist",
    domain: "Maths",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Coding", "AI", "Analytics"],
    suitableLearningStyles: ["Practice-based", "Mixed", "Theory"],
    requiredResources: ["Laptop", "Internet", "Python/R"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Analyze large datasets, create predictive models, and extract insights using statistics and machine learning."
  },
  {
    name: "Financial Analyst",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Business", "Finance"],
    suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Books", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Assess investment opportunities and financial performance using quantitative methods."
  },
  {
    name: "Econometrician",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Maths", "Economics", "Statistics"],
    suitableLearningStyles: ["Theory", "Mixed", "Practice-based"],
    requiredResources: ["Books", "Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Use mathematical and statistical techniques to study economic data and forecast trends."
  },
  {
    name: "Cryptographer / Cryptanalyst",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Maths", "Coding", "Security"],
    suitableLearningStyles: ["Theory", "Practice-based"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Design secure communication systems and analyze cryptographic algorithms using advanced mathematics."
  },
  {
    name: "Mathematical Modeler",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Physics", "Engineering"],
    suitableLearningStyles: ["Theory + Practice", "Mixed"],
    requiredResources: ["Books", "Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Develop mathematical models to simulate real-world systems and predict outcomes."
  },
  {
    name: "AI / ML Analytics Specialist",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Maths", "Coding", "AI"],
    suitableLearningStyles: ["Practice-based", "Theory", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Python/R"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Combine mathematics and AI to extract insights from data and build predictive analytics solutions."
  },
  {
    name: "Astronomer / Astrophysicist",
    domain: "Maths",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Maths", "Physics", "Space Science"],
    suitableLearningStyles: ["Theory", "Mixed", "Practice-based"],
    requiredResources: ["Books", "Internet", "Telescopes (optional)"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Study celestial objects and phenomena using mathematics and physics. Can contribute to space missions or research."
  },
  {
    name: "Operations Analyst",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Business"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Use mathematical and analytical techniques to improve business or organizational efficiency."
  },
  {
    name: "Astronaut / Space Mission Specialist",
    domain: "Maths",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Maths", "Physics", "Engineering", "Space Science"],
    suitableLearningStyles: ["Practice-based", "Theory", "Mixed"],
    requiredResources: ["Physical Fitness", "Training Facilities", "Laptop", "Internet"],
    minimumStudyTime: 5,
    difficulty: "Extremely High",
    riskLevel: "High",
    description: "Train for space missions, scientific research, and experiments in microgravity. Requires strong analytical, physical, and problem-solving skills."
  },
  {
    name: "Supply Chain / Logistics Analyst",
    domain: "Maths",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Business", "Analytics"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Optimize supply chains and logistics using mathematical models and data analytics."
  },
  {
    name: "Climate / Environmental Analyst",
    domain: "Maths",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Maths", "Science", "Environment"],
    suitableLearningStyles: ["Practice-based", "Theory", "Mixed"],
    requiredResources: ["Laptop", "Books", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Use mathematics and data to study climate patterns, environmental risks, and predictive models for sustainability."
  }
,



// ===================== DESIGN & CREATIVE =====================
// ===================== DESIGN & CREATIVE =====================

  {
    name: "UI/UX Designer",
    domain: "Design",
    suitableEducationLevels: ["Class 11–12", "College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Coding"],
    suitableLearningStyles: ["Visual", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Design intuitive interfaces and improve user experience for websites and apps."
  },
  {
    name: "Graphic Designer",
    domain: "Design",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design"],
    suitableLearningStyles: ["Visual"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Create visual content for digital and print media using graphic design tools."
  },
  {
    name: "Product Designer",
    domain: "Design",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Design", "Business"],
    suitableLearningStyles: ["Visual", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design and develop physical or digital products with user-focused solutions."
  },
  {
    name: "Motion Graphics / Animator",
    domain: "Design",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Coding"],
    suitableLearningStyles: ["Visual", "Practice-based"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Create animations and motion graphics for media, advertisements, and films."
  },
  {
    name: "Game Designer",
    domain: "Design",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Coding"],
    suitableLearningStyles: ["Visual", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Design engaging gameplay mechanics, levels, and storylines for video games."
  },
  {
    name: "Industrial Designer",
    domain: "Design",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Business"],
    suitableLearningStyles: ["Visual", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Field Equipment"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design physical products, tools, and equipment combining functionality and aesthetics."
  },
  {
    name: "Interior Designer",
    domain: "Design",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Architecture", "Creativity"],
    suitableLearningStyles: ["Visual", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Design Tools"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Plan and design interior spaces combining aesthetics, functionality, and ergonomics."
  },
  {
    name: "Architect",
    domain: "Design",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Design", "Engineering", "Creativity"],
    suitableLearningStyles: ["Visual", "Theory", "Practice-based"],
    requiredResources: ["Laptop", "Internet", "Design Software"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Design buildings and structures balancing creativity, engineering, and usability."
  },
  {
    name: "Fashion Designer",
    domain: "Design",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Creativity", "Art"],
    suitableLearningStyles: ["Visual", "Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Fabric / Materials"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design clothing, accessories, and fashion lines combining aesthetics and trends."
  },
  {
    name: "Photographer / Videographer",
    domain: "Design",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Art", "Creativity"],
    suitableLearningStyles: ["Practice-based", "Visual"],
    requiredResources: ["Camera", "Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Capture and edit photos and videos for media, events, or art projects."
  },
  {
    name: "Advertising / Marketing Designer",
    domain: "Design",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Business", "Creativity"],
    suitableLearningStyles: ["Visual", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Design Software"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Create visual content and campaigns for branding, marketing, and advertisements."
  },
  {
    name: "Illustrator / Concept Artist",
    domain: "Design",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Art", "Creativity"],
    suitableLearningStyles: ["Visual", "Practice-based"],
    requiredResources: ["Laptop", "Drawing Tools", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Create artwork for books, games, films, advertisements, and other media."
  },
  {
    name: "Creative Director",
    domain: "Design",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Design", "Art", "Business"],
    suitableLearningStyles: ["Visual", "Mixed"],
    requiredResources: ["Laptop", "Internet"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Lead creative teams to conceptualize, design, and execute visual and artistic projects."
  },
  {
    name: "Set Designer / Stage Designer",
    domain: "Design",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Art", "Creativity"],
    suitableLearningStyles: ["Visual", "Practice-based"],
    requiredResources: ["Laptop", "Internet", "Field Tools"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design and create sets for theatre, movies, or events, combining aesthetics and functionality."
  },
  {
    name: "AR / VR Designer",
    domain: "Design",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Design", "3D Modeling", "Creativity", "Tech"],
    suitableLearningStyles: ["Visual", "Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "VR/AR Equipment"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Design immersive experiences in augmented and virtual reality for games, training, and media."
  },
  {
    name: "Video Game Artist / Environment Artist",
    domain: "Design",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Creativity", "Gaming"],
    suitableLearningStyles: ["Visual", "Practice-based"],
    requiredResources: ["Laptop", "Internet", "3D Software"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design characters, environments, and visual assets for video games and interactive media."
  },
  {
    name: "Interior Stylist / Decorator",
    domain: "Design",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Design", "Creativity", "Art"],
    suitableLearningStyles: ["Visual", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Design Tools"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Style and decorate interior spaces focusing on aesthetics and functionality."
  }
,


// ===================== BUSINESS & MANAGEMENT =====================
// ===================== BUSINESS & MANAGEMENT =====================

  {
    name: "Business Analyst",
    domain: "Business",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "Analytics", "Maths"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Analyze business processes, identify improvements, and provide data-driven insights."
  },
  {
    name: "Management Consultant",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Business", "Strategy", "Problem Solving"],
    suitableLearningStyles: ["Theory", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Advise organizations on business strategies, operations, and management challenges."
  },
  {
    name: "Entrepreneur / Startup Founder",
    domain: "Business",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Business", "Innovation", "Leadership"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Capital / Resources"],
    minimumStudyTime: 3,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Start and run your own business, creating innovative products or services."
  },
  {
    name: "Financial Analyst",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Finance", "Maths", "Business"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Analyze financial data, investment opportunities, and company performance."
  },
  {
    name: "Investment Banker",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Finance", "Business", "Maths"],
    suitableLearningStyles: ["Theory", "Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Manage large financial transactions, capital raising, mergers, and acquisitions."
  },
  {
    name: "Marketing Manager",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "Creativity", "Strategy"],
    suitableLearningStyles: ["Mixed", "Visual", "Practice-based"],
    requiredResources: ["Laptop", "Internet", "Marketing Tools"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Plan and execute marketing strategies to promote products and services."
  },
  {
    name: "Human Resources Manager",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "People Management", "Communication"],
    suitableLearningStyles: ["Mixed", "Practice-based"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Manage recruitment, employee relations, performance, and organizational culture."
  },
  {
    name: "Operations Manager",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "Management", "Logistics"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Oversee daily business operations, optimize processes, and improve efficiency."
  },
  {
    name: "Supply Chain / Logistics Manager",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "Logistics", "Analytics"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Manage and optimize supply chains, inventory, and logistics operations."
  },
  {
    name: "Project Manager",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "Leadership", "Organization"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Project Management Tools"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Plan, execute, and oversee projects ensuring they meet objectives, budget, and timelines."
  },
  {
    name: "Business Development Manager",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "Strategy", "Sales"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Identify business opportunities, build relationships, and grow company revenue."
  },
  {
    name: "Management Information Systems (MIS) Analyst",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "Analytics", "IT"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Software Tools"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Manage and analyze business information systems to support decision-making."
  },
  {
    name: "Entrepreneurship / Innovation Specialist",
    domain: "Business",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Business", "Innovation", "Strategy"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books", "Capital"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Develop new business ideas, products, or startups, and guide innovation strategy."
  },
  {
    name: "Retail / E-commerce Manager",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "Marketing", "Sales"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Retail Tools"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Oversee retail or e-commerce operations, sales strategies, and customer engagement."
  },
  {
    name: "Corporate Strategist",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Business", "Strategy", "Leadership"],
    suitableLearningStyles: ["Theory", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Develop long-term strategies for corporate growth and market competitiveness."
  },
  {
    name: "Risk Manager",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Business", "Finance", "Analytics"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Identify and manage financial, operational, or strategic risks for a business."
  },
  {
    name: "Consulting Analyst",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Business", "Strategy", "Analytics"],
    suitableLearningStyles: ["Theory", "Mixed", "Practice-based"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Assist consulting firms with data analysis, business research, and client strategy."
  },
  {
    name: "International Business Manager",
    domain: "Business",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Business", "Strategy", "Global Markets"],
    suitableLearningStyles: ["Theory", "Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Manage business operations and strategy across international markets and cultures."
  }
,


// ===================== COMMERCE / FINANCE =====================
// ===================== COMMERCE & FINANCE =====================


  {
    name: "Chartered Accountant (CA)",
    domain: "Commerce",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Commerce", "Maths"],
    suitableLearningStyles: ["Reading"],
    requiredResources: ["Books", "Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Manage financial accounts, auditing, and taxation for businesses and individuals."
  },
  {
    name: "Company Secretary (CS)",
    domain: "Commerce",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Commerce", "Law"],
    suitableLearningStyles: ["Reading"],
    requiredResources: ["Books", "Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Ensure compliance with company laws and corporate governance requirements."
  },
  {
    name: "Financial Analyst",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Commerce", "Maths", "Business"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Analyze financial data to assist in investment and business decisions."
  },
  {
    name: "Investment Banker",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Commerce", "Maths", "Business"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 4,
    difficulty: "High",
    riskLevel: "High",
    description: "Manage investments, capital raising, and financial strategy for clients."
  },
  {
    name: "Stock Market Analyst",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Commerce", "Maths"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Analyze market trends and advise on investment decisions."
  },
  {
    name: "Tax Consultant",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Commerce", "Maths"],
    suitableLearningStyles: ["Reading"],
    requiredResources: ["Books", "Laptop", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Provide guidance on taxation and compliance for individuals or companies."
  },
  {
    name: "Auditor",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Commerce", "Maths", "Accounting"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Examine financial records and ensure accuracy and compliance with regulations."
  },
  {
    name: "Risk Manager",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Commerce", "Finance", "Analytics"],
    suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Identify, assess, and mitigate financial and operational risks for businesses."
  },
  {
    name: "Treasury Manager",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Finance", "Commerce", "Maths"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Manage a company's cash flow, investments, and financial planning."
  },
  {
    name: "Credit Analyst",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Finance", "Commerce", "Analytics"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Assess creditworthiness of individuals or companies for lending decisions."
  },
  {
    name: "Insurance Analyst / Underwriter",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Finance", "Commerce", "Risk Management"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Evaluate insurance applications, determine premiums, and manage risk portfolios."
  },
  {
    name: "Portfolio Manager",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Finance", "Commerce", "Investments"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Manage investment portfolios for clients or institutions to maximize returns."
  },
  {
    name: "Wealth Manager / Private Banker",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Finance", "Commerce", "Client Relations"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Provide personalized financial planning and investment advice to high-net-worth clients."
  },
  {
    name: "Financial Planner",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Finance", "Commerce", "Maths"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Help individuals plan their finances, investments, retirement, and savings."
  },
  {
    name: "Forex / Commodity Trader",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Finance", "Commerce", "Markets"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Trading Platforms"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Buy and sell currencies or commodities to earn profits from market fluctuations."
  },
  {
    name: "FinTech Specialist",
    domain: "Commerce",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Commerce", "Finance", "Technology"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Software Tools"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Develop or manage financial technology products and solutions, like digital payments or blockchain platforms."
  },
  {
    name: "Accounting Manager",
    domain: "Commerce",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Accounting", "Finance", "Commerce"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Oversee accounting operations, financial reporting, and compliance for organizations."
  }
,


// ===================== HEALTHCARE / MEDICAL =====================
// ===================== HEALTHCARE & MEDICINE =====================

  {
    name: "Doctor (MBBS)",
    domain: "Healthcare",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Medical & Healthcare", "Science"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "Internet", "Lab Equipment"],
    minimumStudyTime: 4,
    difficulty: "High",
    riskLevel: "High",
    description: "Diagnose and treat patients through clinical practice. Requires long-term dedication and strong science background."
  },
  {
    name: "Surgeon",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Medical & Healthcare", "Science", "Precision Work"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Books", "Internet", "Surgical Equipment"],
    minimumStudyTime: 5,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Perform surgical procedures to treat injuries, diseases, and deformities."
  },
  {
    name: "Nurse",
    domain: "Healthcare",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Books", "Internet", "Clinical Training"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Assist doctors and care for patients in hospitals and clinics."
  },
  {
    name: "Pharmacist",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare", "Chemistry"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "Internet", "Lab Equipment"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Prepare and dispense medicines while advising patients on proper usage."
  },
  {
    name: "Physiotherapist",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare", "Fitness"],
    suitableLearningStyles: ["Practice-based"],
    requiredResources: ["Books", "Internet", "Clinical Equipment"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Help patients recover movement and strength after injury or illness."
  },
  {
    name: "Medical Lab Technician",
    domain: "Healthcare",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average"],
    suitableInterests: ["Medical & Healthcare", "Science"],
    suitableLearningStyles: ["Practice-based"],
    requiredResources: ["Lab Equipment", "Books", "Internet"],
    minimumStudyTime: 1,
    difficulty: "Low",
    riskLevel: "Low",
    description: "Conduct medical tests and lab investigations to assist diagnosis."
  },
  {
    name: "Public Health Analyst",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare", "Social Work", "Data Analysis"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Analyze health data and design programs to improve public health outcomes."
  },
  {
    name: "Occupational Therapist",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare", "Therapy", "Rehabilitation"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Books", "Clinical Equipment", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Help patients regain daily living and work skills after injury or illness."
  },
  {
    name: "Speech Therapist / Pathologist",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare", "Communication"],
    suitableLearningStyles: ["Practice-based", "Reading"],
    requiredResources: ["Books", "Clinical Equipment", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Diagnose and treat speech, language, and communication disorders."
  },
  {
    name: "Radiologist",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Medical & Healthcare", "Diagnostics", "Technology"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "MRI/CT Machines", "Internet"],
    minimumStudyTime: 4,
    difficulty: "Very High",
    riskLevel: "High",
    description: "Interpret medical imaging to diagnose diseases and injuries."
  },
  {
    name: "Clinical Researcher / Scientist",
    domain: "Healthcare",
    suitableEducationLevels: ["College", "Masters", "PhD"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Medical & Healthcare", "Research", "Science"],
    suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
    requiredResources: ["Lab Equipment", "Books", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Conduct research studies and trials to develop new treatments and medical knowledge."
  },
  {
    name: "Nutritionist / Dietitian",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare", "Fitness", "Biology"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "Internet", "Lab Tools"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Low",
    description: "Provide dietary guidance to improve health and manage medical conditions."
  },
  {
    name: "Mental Health Counselor / Psychologist",
    domain: "Healthcare",
    suitableEducationLevels: ["College", "Masters"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare", "Psychology", "Social Work"],
    suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
    requiredResources: ["Books", "Internet", "Counseling Tools"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Assess and treat mental health issues through therapy and counseling."
  },
  {
    name: "Epidemiologist",
    domain: "Healthcare",
    suitableEducationLevels: ["College", "Masters"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare", "Research", "Data Analysis"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Study patterns and causes of diseases to inform public health policies and interventions."
  },
  {
    name: "Biomedical Engineer",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Medical & Healthcare", "Engineering", "Technology"],
    suitableLearningStyles: ["Practice-based", "Mixed"],
    requiredResources: ["Lab Equipment", "Laptop", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Design and develop medical devices, prosthetics, and healthcare technology solutions."
  },
  {
    name: "Healthcare Administrator / Hospital Manager",
    domain: "Healthcare",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Management", "Healthcare", "Leadership"],
    suitableLearningStyles: ["Mixed", "Reading"],
    requiredResources: ["Laptop", "Internet", "Books"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Oversee hospital operations, staff, and healthcare services to ensure efficiency and quality."
  },
  {
    name: "Paramedic / Emergency Medical Technician (EMT)",
    domain: "Healthcare",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Medical & Healthcare", "Emergency Care"],
    suitableLearningStyles: ["Practice-based"],
    requiredResources: ["Books", "Internet", "Emergency Equipment"],
    minimumStudyTime: 1,
    difficulty: "Medium",
    riskLevel: "High",
    description: "Provide emergency medical care and transport patients to hospitals."
  },
  {
    name: "Genetic Counselor / Geneticist",
    domain: "Healthcare",
    suitableEducationLevels: ["College", "Masters"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Medical & Healthcare", "Genetics", "Research"],
    suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
    requiredResources: ["Lab Equipment", "Books", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "Medium",
    description: "Analyze genetic data to advise patients on inherited conditions and health risks."
  }


,
// ===================== GOVERNMENT EXAMS =====================
// ===================== GOVERNMENT EXAMS & STUDY ABROAD =====================

  // Domestic Civil Services
  {
    name: "UPSC (IAS/IPS/IFS)",
    domain: "Government",
    suitableEducationLevels: ["College", "Dropper / Gap Year"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Government Exams", "History", "Polity"],
    suitableLearningStyles: ["Reading"],
    requiredResources: ["Books", "Internet"],
    minimumStudyTime: 4,
    difficulty: "High",
    riskLevel: "High",
    description: "Prepare for top-level civil services exams in India. Requires dedication and consistent study."
  },
  {
    name: "SSC (Staff Selection Commission)",
    domain: "Government",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Government Exams"],
    suitableLearningStyles: ["Reading"],
    requiredResources: ["Books", "Internet"],
    minimumStudyTime: 3,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Prepare for Staff Selection Commission exams to join various government departments."
  },
  {
    name: "Banking (PO/Clerk)",
    domain: "Government",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Government Exams", "Commerce"],
    suitableLearningStyles: ["Reading"],
    requiredResources: ["Books", "Internet"],
    minimumStudyTime: 3,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Prepare for banking exams to become a PO or clerk in Indian banks."
  },
  {
    name: "Defence (NDA/CDS/AFCAT)",
    domain: "Government",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Government Exams", "Fitness"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "Internet", "Physical Training"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Prepare for Indian Armed Forces exams to become an officer."
  },
  {
    name: "Teaching (TET/CTET)",
    domain: "Government",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Government Exams", "Education"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Books", "Internet"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "Medium",
    description: "Qualify state or central teaching exams to become a certified teacher."
  },

  // Judiciary & Legal Services
  {
    name: "Judiciary (CLAT Judicial / State Judicial Services)",
    domain: "Government",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Law", "Government Exams"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Books", "Internet"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Qualify exams to become judges or legal officers in government services."
  },
  {
    name: "Police / Law Enforcement (State Police Exams / IPS)",
    domain: "Government",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Government Exams", "Law", "Public Service"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "Internet", "Physical Training"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Qualify police service exams to join law enforcement agencies at state or national level."
  },

  // Defense & Paramilitary
  {
    name: "Paramilitary & Armed Forces (BSF, CRPF, ITBP, Coast Guard, Navy, Army Technical)",
    domain: "Government",
    suitableEducationLevels: ["Class 11–12", "College"],
    suitableComfortLevels: ["Average", "Strong"],
    suitableInterests: ["Government Exams", "Fitness", "Security", "Technical Skills"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "Internet", "Physical Training", "Lab/Technical Equipment"],
    minimumStudyTime: 2,
    difficulty: "Medium",
    riskLevel: "High",
    description: "Qualify exams to join paramilitary and defense forces for national security and technical roles."
  },

  // International Civil & Administrative Services
  {
    name: "Foreign Civil Services (USA, UK, Canada, UN, International Organizations)",
    domain: "Government",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Government Exams", "International Relations", "Policy Making"],
    suitableLearningStyles: ["Reading", "Mixed"],
    requiredResources: ["Books", "Internet"],
    minimumStudyTime: 4,
    difficulty: "High",
    riskLevel: "High",
    description: "Qualify national or international civil service exams to serve in government administration abroad."
  },
  {
    name: "Judicial / Law Enforcement Abroad (FBI, CIA, Scotland Yard, Interpol)",
    domain: "Government",
    suitableEducationLevels: ["College"],
    suitableComfortLevels: ["Strong"],
    suitableInterests: ["Government Exams", "Law", "Security"],
    suitableLearningStyles: ["Reading", "Practice-based"],
    requiredResources: ["Books", "Internet", "Physical Training"],
    minimumStudyTime: 3,
    difficulty: "High",
    riskLevel: "High",
    description: "Qualify exams or training to join law enforcement and intelligence agencies internationally."
  },

  


// ===================== MIXED / SAFE / ALTERNATIVE =====================
{
name: "Teaching / Education",
domain: "Mixed",
suitableEducationLevels: ["Class 11–12", "College"],
suitableComfortLevels: ["Beginner", "Average", "Strong"],
suitableInterests: ["Education", "Science", "Maths"],
suitableLearningStyles: ["Visual", "Reading", "Mixed"],
requiredResources: ["Books", "Laptop", "Internet"],
minimumStudyTime: 1,
difficulty: "Low",
riskLevel: "Low",
description: "Teach students in schools or online. Suitable for patient and organized individuals."
},
{
name: "Skill-based Freelancing",
domain: "Mixed",
suitableEducationLevels: ["Class 11–12", "College", "Dropper / Gap Year"],
suitableComfortLevels: ["Beginner", "Average", "Strong"],
suitableInterests: ["Coding", "Design", "Business"],
suitableLearningStyles: ["Practice-based", "Mixed"],
requiredResources: ["Laptop", "Internet"],
minimumStudyTime: 1,
difficulty: "Low",
riskLevel: "Low",
description: "Offer freelance services like coding, design, or marketing online."
},
{
name: "Content Creator",
domain: "Mixed",
suitableEducationLevels: ["Class 11–12", "College", "Dropper / Gap Year"],
suitableComfortLevels: ["Average", "Strong"],
suitableInterests: ["Design", "Business", "Coding"],
suitableLearningStyles: ["Visual", "Mixed"],
requiredResources: ["Laptop", "Smartphone", "Internet"],
minimumStudyTime: 1,
difficulty: "Medium",
riskLevel: "Medium",
description: "Create engaging online content on platforms like YouTube, Instagram, or blogs."
},
{
name: "Technical Support Engineer",
domain: "Mixed",
suitableEducationLevels: ["Class 11–12", "College"],
suitableComfortLevels: ["Beginner", "Average"],
suitableInterests: ["Coding", "Business"],
suitableLearningStyles: ["Practice-based", "Mixed"],
requiredResources: ["Laptop", "Internet"],
minimumStudyTime: 1,
difficulty: "Medium",
riskLevel: "Low",
description: "Assist users in solving technical problems with software or hardware."
},
{
name: "Career Counselor",
domain: "Mixed",
suitableEducationLevels: ["College", "Dropper / Gap Year"],
suitableComfortLevels: ["Average", "Strong"],
suitableInterests: ["Education", "Business", "Social Work"],
suitableLearningStyles: ["Reading", "Mixed"],
requiredResources: ["Laptop", "Internet", "Books"],
minimumStudyTime: 2,
difficulty: "Medium",
riskLevel: "Low",
description: "Guide students or professionals to choose suitable career paths."
},
{
name: "NGO / Social Work",
domain: "Mixed",
suitableEducationLevels: ["College"],
suitableComfortLevels: ["Average", "Strong"],
suitableInterests: ["Social Work", "Business", "Education"],
suitableLearningStyles: ["Reading", "Visual", "Mixed"],
requiredResources: ["Books", "Internet"],
minimumStudyTime: 2,
difficulty: "Medium",
riskLevel: "Low",
description: "Work in non-profits or social service organizations to create impact."
}
// CareerData.js
,
  // ===================== Existing Careers =====================
  // ... your existing career objects here ...
  
  // ===================== NEW DOMAINS =====================
  
  // 1. Space / Astronomy
  {
  name: "Astrophysicist",
  domain: "Space / Astronomy",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Space", "Physics", "Maths"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet", "Observatory Access"],
  minimumStudyTime: 4,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Study celestial objects and phenomena using theoretical and observational methods."
},
{
  name: "Satellite Engineer",
  domain: "Space / Astronomy",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Space", "Engineering", "Coding"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Lab Access"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Design, build, and maintain satellites for research or communication purposes."
},
{
  name: "Astronomer",
  domain: "Space / Astronomy",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Space", "Physics", "Maths"],
  suitableLearningStyles: ["Reading", "Practice-based"],
  requiredResources: ["Books", "Internet", "Observatory Access"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Observe and analyze astronomical data to understand the universe."
},
{
  name: "Planetary Scientist",
  domain: "Space / Astronomy",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Space", "Geology", "Physics"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet", "Lab Access"],
  minimumStudyTime: 4,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Study planets, moons, and other bodies in the solar system to understand their composition and evolution."
},
{
  name: "Mission Control Specialist / Space Operations Engineer",
  domain: "Space / Astronomy",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Space", "Engineering", "Problem Solving"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Simulation Tools"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "High",
  description: "Monitor and control space missions, ensuring spacecraft operations and communications run smoothly."
}
,
  // 2. Environment / Sustainability
  {
  name: "Environmental Scientist",
  domain: "Environment / Sustainability",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Environment", "Science", "Research"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Internet", "Field Equipment"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Analyze environmental issues and propose sustainable solutions."
},
{
  name: "Sustainability Consultant",
  domain: "Environment / Sustainability",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Business", "Environment", "Policy"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Books"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Advise organizations on sustainable practices and environmental compliance."
},
{
  name: "Climate Analyst",
  domain: "Environment / Sustainability",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Environment", "Maths", "Science"],
  suitableLearningStyles: ["Reading", "Practice-based"],
  requiredResources: ["Laptop", "Internet", "Data Access"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Analyze climate data and predict environmental trends."
},
{
  name: "Renewable Energy Engineer",
  domain: "Environment / Sustainability",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Engineering", "Environment", "Technology"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Lab Equipment", "Laptop", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Design and implement renewable energy solutions like solar, wind, and hydro systems."
},
{
  name: "Conservation Biologist",
  domain: "Environment / Sustainability",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Environment", "Biology", "Research"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Field Equipment", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Low",
  description: "Protect ecosystems and endangered species through research, policy, and fieldwork."
}

 , // 3. Agriculture / Food Science
 
{
  name: "Agricultural Scientist",
  domain: "Agriculture / Food Science",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Biology", "Science", "Environment"],
  suitableLearningStyles: ["Practice-based", "Reading", "Mixed"],
  requiredResources: ["Books", "Internet", "Lab/Field Access"],
  minimumStudyTime: 3,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Research crops, soil, and farming techniques to improve food production."
},
{
  name: "Food Technologist",
  domain: "Agriculture / Food Science",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Chemistry", "Biology", "Food Science"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Lab Equipment", "Books", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Develop safe and nutritious food products and improve processing methods."
},
{
  name: "Agricultural Policy Analyst",
  domain: "Agriculture / Food Science",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Environment", "Policy", "Economics"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Analyze agricultural policies and advise governments or NGOs."
},
{
  name: "Soil Scientist",
  domain: "Agriculture / Food Science",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Biology", "Chemistry", "Environment"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Lab/Field Equipment", "Books", "Internet"],
  minimumStudyTime: 3,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Study soil properties and their impact on crop growth and ecosystem health."
},
{
  name: "Agri-Business Manager",
  domain: "Agriculture / Food Science",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Business", "Agriculture", "Economics"],
  suitableLearningStyles: ["Mixed", "Reading"],
  requiredResources: ["Laptop", "Internet", "Books"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Manage agricultural enterprises, supply chains, and farm-based businesses."
}
,
  // 4. Law / Judiciary
 {
  name: "Lawyer",
  domain: "Law / Judiciary",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Law", "Politics", "Social Work"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Internet", "Court Access"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "High",
  description: "Provide legal counsel, represent clients, and interpret laws. Prepare for exams like Bar Council Exams (India/US), LSAT, and national law entrance exams."
},
{
  name: "Judge",
  domain: "Law / Judiciary",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Law", "Social Work", "Politics"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Internet", "Court Access"],
  minimumStudyTime: 5,
  difficulty: "High",
  riskLevel: "High",
  description: "Preside over court cases and ensure justice. Candidates usually clear judicial service exams like Indian Judicial Service, US Bar (if practicing abroad), or state-level judiciary exams."
},
{
  name: "Corporate Lawyer",
  domain: "Law / Judiciary",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Law", "Business"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Advise companies on contracts, mergers, compliance, and corporate governance. Prepare for corporate law entrance exams, Bar exams, or specialized international certifications."
},
{
  name: "Legal Advisor / Consultant",
  domain: "Law / Judiciary",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Law", "Business", "Policy"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Provide legal guidance for businesses, NGOs, or individuals. May require Bar Exams, LSAT, or certifications like Certified Compliance Professional (CCP)."
},
{
  name: "Civil Services / Judicial Exam Aspirant",
  domain: "Law / Judiciary",
  suitableEducationLevels: ["College", "Dropper / Gap Year"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Law", "Polity", "Administration"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Internet", "Study Material"],
  minimumStudyTime: 4,
  difficulty: "High",
  riskLevel: "High",
  description: "Prepare for judicial or civil services exams like Indian Judicial Service, UPSC Judicial Exams, All India Bar Exam, or international law exams to enter judiciary or administrative roles."
}
,
  // 5. Media / Journalism / Communication
{
  name: "Journalist",
  domain: "Media / Journalism / Communication",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Writing", "Media", "Politics"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Camera"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Investigate, report, and present news stories to the public. Prepare for journalism entrance exams, such as BJMC, MJMC, or international certifications like Reuters Journalism Program, or study-abroad exams for media programs."
},
{
  name: "Content Strategist",
  domain: "Media / Journalism / Communication",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Media", "Business", "Design"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Plan and manage digital content for marketing and communications. Relevant exams include digital marketing certifications, media management courses, or GRE/GMAT for international media management programs."
},
{
  name: "Public Relations Specialist",
  domain: "Media / Journalism / Communication",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Media", "Business", "Communication"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Manage public image and communications for organizations or individuals. Can prepare for PR certifications, communications exams, or study abroad programs in Media and Communication."
},
{
  name: "Broadcast Journalist / Reporter",
  domain: "Media / Journalism / Communication",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Media", "Politics", "Communication"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Laptop", "Camera", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Report news on TV, radio, or digital platforms. Prepare for journalism entrance exams, broadcast certifications, or international media programs."
},
{
  name: "Social Media Manager",
  domain: "Media / Journalism / Communication",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Media", "Marketing", "Communication"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Smartphone"],
  minimumStudyTime: 1,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Manage and grow social media presence for brands or organizations. Relevant exams/certifications include Google Digital Marketing, HubSpot Social Media Certification, or GRE/GMAT for international media management courses."
},
{
  name: "Investigative Reporter",
  domain: "Media / Journalism / Communication",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Research", "Media", "Law"],
  suitableLearningStyles: ["Reading", "Practice-based"],
  requiredResources: ["Laptop", "Internet", "Access to archives"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Conduct deep investigations for news stories. Prepares students for journalism certifications, law-related media courses, or study abroad in investigative journalism programs."
}
,

  // 6. Sports / Fitness / Coaching
{
  name: "Fitness Trainer / Personal Trainer",
  domain: "Sports / Fitness / Coaching",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Fitness", "Sports", "Health"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Gym Access", "Books", "Internet"],
  minimumStudyTime: 1,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Design personalized fitness programs for individuals or groups. Can pursue certifications like ACE, ISSA, NASM, or international sports science programs."
},
{
  name: "Athletic Coach",
  domain: "Sports / Fitness / Coaching",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Sports", "Fitness", "Team Management"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Sports Facilities", "Internet", "Books"],
  minimumStudyTime: 2,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Train athletes for competitions and improve performance. Prepare for coaching certifications (NIS, NSCA) or international coaching programs."
},
{
  name: "Sports Scientist",
  domain: "Sports / Fitness / Coaching",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Sports", "Science", "Health"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Lab/Field Access", "Books", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Analyze athletic performance and develop evidence-based training programs. Can pursue certifications in sports science or study abroad programs in Exercise Science or Kinesiology."
},
{
  name: "Physiotherapist (Sports Rehab)",
  domain: "Sports / Fitness / Coaching",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Health", "Sports", "Science"],
  suitableLearningStyles: ["Practice-based", "Reading"],
  requiredResources: ["Clinic Access", "Books", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Help athletes recover from injuries and improve mobility. Can pursue physiotherapy certifications, sports rehab programs, or international physiotherapy exams (like US-licensed PT programs)."
},
{
  name: "Nutritionist / Sports Dietitian",
  domain: "Sports / Fitness / Coaching",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Nutrition", "Health", "Fitness"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Internet", "Lab Access"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Design nutrition plans for athletes and individuals. Can pursue certifications like ISSN, sports dietitian programs, or international nutrition diplomas."
},
{
  name: "Sports Analyst / Performance Analyst",
  domain: "Sports / Fitness / Coaching",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Sports", "Data Analysis", "Technology"],
  suitableLearningStyles: ["Practice-based", "Reading", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Sports Data Access"],
  minimumStudyTime: 2,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Analyze team and player performance using data. Relevant certifications include sports analytics courses, FIFA/IOC coaching programs, or international sports data programs."
}

,
  // 7. Emerging Technology / AI / Robotics
  {
  name: "AI Engineer",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Coding", "Maths", "AI"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Books"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Develop AI models, algorithms, and applications for real-world problems."
},
{
  name: "Robotics Engineer",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Coding", "Mechanical", "Electronics"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Lab Equipment", "Laptop", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Design, build, and program robotic systems for various industries."
},
{
  name: "Data Scientist",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Maths", "Coding", "AI"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Books"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Analyze complex data sets and create predictive models using AI."
},
{
  name: "Machine Learning Researcher",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["College", "Masters", "PhD"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["AI", "Maths", "Research"],
  suitableLearningStyles: ["Reading", "Practice-based"],
  requiredResources: ["Laptop", "Internet", "Research Papers"],
  minimumStudyTime: 4,
  difficulty: "High",
  riskLevel: "High",
  description: "Conduct advanced research to develop new machine learning algorithms and AI systems."
},
{
  name: "Automation Engineer",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Mechanical", "Electronics", "Coding"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Lab Equipment", "Laptop", "Internet"],
  minimumStudyTime: 3,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Develop automated systems for manufacturing, logistics, and industrial processes."
},
{
  name: "Computer Vision Engineer",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["College", "Masters"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["AI", "Maths", "Coding"],
  suitableLearningStyles: ["Practice-based", "Reading"],
  requiredResources: ["Laptop", "Internet", "Camera/Hardware"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Build AI systems that interpret and analyze visual data from images and videos."
},
{
  name: "Natural Language Processing (NLP) Engineer",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["College", "Masters"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["AI", "Linguistics", "Coding"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Datasets"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Develop AI systems that understand, interpret, and generate human language."
},
{
  name: "Quantum Computing Researcher",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["Masters", "PhD"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Physics", "Maths", "AI"],
  suitableLearningStyles: ["Reading", "Research-based"],
  requiredResources: ["Lab Access", "Laptop", "Internet", "Quantum Simulator"],
  minimumStudyTime: 5,
  difficulty: "High",
  riskLevel: "High",
  description: "Research and develop algorithms for quantum computers and quantum AI systems."
},
{
  name: "AI Product Manager",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Business", "AI", "Tech Management"],
  suitableLearningStyles: ["Mixed"],
  requiredResources: ["Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Oversee AI product development, bridge technical and business teams, and manage strategy."
},
{
  name: "Drone / UAV Engineer",
  domain: "Emerging Technology / AI / Robotics",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Mechanical", "Electronics", "AI"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Lab Equipment", "Laptop", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Design and program drones for industrial, research, or defense applications."
}
,

  // 8. Defense / Cybersecurity / Strategic Studies
{
  name: "Military Officer",
  domain: "Defense / Cybersecurity / Strategic Studies",
  suitableEducationLevels: ["College", "Defense Academy"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Defense", "Strategy", "Fitness"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Physical Training", "Books", "Internet"],
  minimumStudyTime: 4,
  difficulty: "High",
  riskLevel: "High",
  description: "Lead military units, plan strategic operations, and ensure national security."
},
{
  name: "Army Officer (NDA / CDS)",
  domain: "Defense / Cybersecurity / Strategic Studies",
  suitableEducationLevels: ["Class 11–12", "College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Defense", "Fitness", "Strategy"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Books", "Physical Training", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "High",
  description: "Join the Indian Army as a commissioned officer via NDA or CDS exams."
},
{
  name: "Navy Officer (NDA / CDS / INET)",
  domain: "Defense / Cybersecurity / Strategic Studies",
  suitableEducationLevels: ["Class 11–12", "College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Defense", "Marine Science", "Fitness"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Books", "Physical Training", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "High",
  description: "Join the Indian Navy as a commissioned officer via NDA, CDS, or INET exams."
},
{
  name: "Air Force Officer (NDA / CDS / AFCAT)",
  domain: "Defense / Cybersecurity / Strategic Studies",
  suitableEducationLevels: ["Class 11–12", "College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Defense", "Aeronautics", "Fitness"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Books", "Physical Training", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "High",
  description: "Join the Indian Air Force as a commissioned officer via NDA, CDS, or AFCAT exams."
},
{
  name: "Intelligence Officer",
  domain: "Defense / Cybersecurity / Strategic Studies",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Defense", "Strategy", "Research"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "High",
  description: "Work in agencies like RAW, IB, or defense intelligence to analyze and act on critical data."
},
{
  name: "Cybersecurity Analyst",
  domain: "Defense / Cybersecurity / Strategic Studies",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Coding", "Security", "Defense"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Books"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Protect networks and systems from cyber threats and attacks."
},
{
  name: "Ethical Hacker / Penetration Tester",
  domain: "Defense / Cybersecurity / Strategic Studies",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Coding", "Security"],
  suitableLearningStyles: ["Practice-based", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Books"],
  minimumStudyTime: 2,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Test systems for vulnerabilities and improve cybersecurity."
},
{
  name: "Defense Strategist / Policy Analyst",
  domain: "Defense / Cybersecurity / Strategic Studies",
  suitableEducationLevels: ["College", "Masters"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Defense", "Politics", "Strategy"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "High",
  description: "Analyze national security policies and design strategic defense plans."
},
{
  name: "Cryptographer",
  domain: "Defense / Cybersecurity / Strategic Studies",
  suitableEducationLevels: ["College", "Masters"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Maths", "Security", "Coding"],
  suitableLearningStyles: ["Reading", "Practice-based"],
  requiredResources: ["Laptop", "Books", "Internet"],
  minimumStudyTime: 4,
  difficulty: "High",
  riskLevel: "High",
  description: "Develop encryption algorithms and secure communication systems for defense and cybersecurity."
}

  ,

  // 9. Study-Abroad / Foreign Exams / Global Education
  
{
  name: "GRE Candidate",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College", "Dropper / Gap Year"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["GRE", "Education", "Global Studies"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Prepare for the GRE (Graduate Record Examination) for admission to graduate programs abroad."
},
{
  name: "GMAT Candidate",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College", "Dropper / Gap Year"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["GMAT", "Business", "Global Studies"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Prepare for the GMAT (Graduate Management Admission Test) for admission to MBA and business schools abroad."
},
{
  name: "SAT Candidate",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["Class 11–12"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["SAT", "Education", "Global Studies"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Prepare for the SAT (Scholastic Assessment Test) for undergraduate admissions abroad."
},
{
  name: "IELTS Candidate",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["Class 11–12", "College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["IELTS", "English", "Language"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Prepare for the IELTS (International English Language Testing System) for admission or migration abroad."
},
{
  name: "TOEFL Candidate",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["Class 11–12", "College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["TOEFL", "English", "Language"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Prepare for the TOEFL (Test of English as a Foreign Language) for admission to universities abroad."
},
{
  name: "LSAT Candidate",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["LSAT", "Law", "Reasoning"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Prepare for the LSAT (Law School Admission Test) for admission to law programs abroad."
},
{
  name: "MCAT Candidate",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["MCAT", "Medical", "Biology", "Chemistry"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Lab Access", "Laptop", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Prepare for the MCAT (Medical College Admission Test) for admission to medical schools abroad."
}
,
{
  name: "International University Applicant",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["Class 11–12", "College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Education", "Global Studies"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Medium",
  description: "Apply for universities abroad using exams like GRE, GMAT, SAT, IELTS, TOEFL, LSAT, or MCAT."
},
{
  name: "Foreign Scholarship Applicant",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["Class 11–12", "College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Education", "Global Studies", "Research"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Prepare for scholarships to study abroad in top universities worldwide."
},
{
  name: "International Exchange Program Participant",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Education", "Global Studies", "Culture"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Books"],
  minimumStudyTime: 1,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Participate in student exchange programs for exposure to foreign universities."
},
{
  name: "Study Abroad Consultant / Counselor",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College", "Masters"],
  suitableComfortLevels: ["Average", "Strong"],
  suitableInterests: ["Education", "Counseling", "Global Studies"],
  suitableLearningStyles: ["Reading", "Mixed"],
  requiredResources: ["Laptop", "Internet", "Books"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Guide students on admissions, visa, and preparation for foreign universities and exams."
},
{
  name: "IELTS / TOEFL Instructor",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College", "Masters"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Education", "Language", "Teaching"],
  suitableLearningStyles: ["Reading", "Practice-based"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Teach English language proficiency courses to prepare students for IELTS/TOEFL exams."
},
{
  name: "GRE / GMAT Tutor",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College", "Masters"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Education", "Maths", "Business", "Reasoning"],
  suitableLearningStyles: ["Reading", "Practice-based", "Mixed"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 2,
  difficulty: "Medium",
  riskLevel: "Low",
  description: "Coach students in quantitative, verbal, and analytical sections for GRE or GMAT exams."
},
{
  name: "Pre-Med / MCAT Coach",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College", "Masters"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Biology", "Chemistry", "Medical Education"],
  suitableLearningStyles: ["Reading", "Practice-based"],
  requiredResources: ["Books", "Lab Access", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Prepare students for MCAT or other medical entrance exams for foreign universities."
},
{
  name: "Law School / LSAT Coach",
  domain: "Study-Abroad / Foreign Exams / Global Education",
  suitableEducationLevels: ["College", "Masters"],
  suitableComfortLevels: ["Strong"],
  suitableInterests: ["Law", "Logic", "Reading"],
  suitableLearningStyles: ["Reading", "Practice-based"],
  requiredResources: ["Books", "Laptop", "Internet"],
  minimumStudyTime: 3,
  difficulty: "High",
  riskLevel: "Medium",
  description: "Guide students to prepare for LSAT and law school admissions abroad."
}



];

module.exports = careers;